name: Build and Publish Exe

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: true

  build_and_publish:
    needs: create_release
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            exe_name: spreadsheet-to-luau.exe
            asset_content_type: application/octet-stream
            build_command: pyinstaller --onefile src/__init__.py -n spreadsheet-to-luau
            zip_suffix: -win64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build exe file
        run: |
          ${{ matrix.build_command }}

      - name: Create ZIP archive and rename executable
        run: |
          mkdir dist-zip
          cp dist/${{ matrix.exe_name }} dist/spreadsheet-to-luau${{ matrix.zip_suffix }}
          7z a dist-zip/spreadsheet-to-luau${{ matrix.zip_suffix }}.zip dist/spreadsheet-to-luau${{ matrix.zip_suffix }}

      - name: Upload zip file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist-zip/spreadsheet-to-luau${{ matrix.zip_suffix }}.zip
          asset_name: spreadsheet-to-luau${{ matrix.zip_suffix }}.zip
          asset_content_type: ${{ matrix.asset_content_type }}
