name: Build and Publish Exe

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build exe file
        run: |
          pyinstaller --onefile --name my_exe src/main.py

      - name: Publish exe file
        uses: actions/upload-artifact@v2
        with:
          name: my_exe
          path: dist/my_exe.exe
