name: release

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        include:
          - os: windows-latest
            exe_name: spreadsheet-to-luau.exe
            asset_content_type: application/octet-stream
          - os: ubuntu-latest
            exe_name: spreadsheet-to-luau
            asset_content_type: application/octet-stream
          - os: macOS-latest
            exe_name: spreadsheet-to-luau
            asset_content_type: application/octet-stream

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: build exe file
        run: |
          pyinstaller --onefile src/__init__.py -n spreadsheet-to-luau

      - name: create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: true

      - name: upload exe file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ matrix.exe_name }}
          asset_name: ${{ matrix.exe_name }}
          asset_content_type: ${{ matrix.asset_content_type }}